---
title: "Informe"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)

data <- read_delim("../data/ROW.csv", 
    ";", escape_double = FALSE, locale = locale(decimal_mark = ",", 
         grouping_mark = "."), trim_ws = TRUE)

cols(
  Adgroup = col_character(),
  MaxCPC = col_double(),
  Clicks = col_integer(),
  Impressions = col_integer(),
  CTR = col_double(),
  AvgCPC = col_double(),
  Costo = col_double(),
  AvgPosicion = col_double(),
  Qscore = col_integer(),
  Ventas = col_integer(),
  Costconv = col_double(),
  Convrate = col_double(),
  Allconv = col_integer()
)


table(data$Adgroup)
```

# Estadística descriptiva

```{r}
dataVE<-subset(data, Adgroup=='Vest English')
dataSE<-subset(data, Adgroup=='Sweater English')  

View(subset(dataSE,Ventas!=0))

cor(dataSE$AvgPosicion,dataSE$Qscore)
cor(dataSE$Clicks,dataSE$CTR)
cor(dataSE$CTR,dataSE$Impressions)

dataSE_1<-dataSE[,c(-1,-13)]
M<-as.matrix(dataSE_1)
cor(M)
plot(dataSE_1)

hist(data$MaxCPC)



summary(data)
data_1<-na.omit(data)

data_2<-data[,-1]
data_3<-as.matrix(data_2)

plot(data_2)

```


